### PR TITLE
Edit default recipe and added new recipe.

### PR DESCRIPTION
**Pull request by joshcangit**
Changed default recipe for **netherite ingot** to **3 netherite scraps** and **3 gold ingots**.

Added recipe to craft **3 netherite nuggets** from a **netherite scrap** and 
**gold ingot**.

### CODE REVIEW

**Comment by joshcangit** [comment]
Only wanted to alter the recipes.
New to the Minecraft Fabric API.
Not sure how to upgrade to 1.17 because of deprecation warning regarding loot table classes.

**Comment by Pepperoni-Jabroni** [comment]
Hmmm, merging this would leave in the existing Netherite Ingot recipe, no? We should remove that if we're changing how the player obtains Netherite Ingots. I worry about the balancing implications of reducing Netherite Ingots from 4 of each to only 3. What are your thoughts on this?

**Comment by joshcangit** [comment]
This will overwrite the existing recipe. This is meant to be proportional to the new recipe I've added here.
If balance is more important than having another way to craft Netherite Nuggets then I suggest just closing this pull request.
I consider this entirely optional so leaving it to you to decide if this should be merged.

**Comment by Pepperoni-Jabroni** [comment]
I prefer not to alter the vanilla recipe for netherite ingots. Thank you for contributing your idea!

**Pull request closed without merging**
